// app/constants/activities.ts

export interface ActivityOption {
  value: string;
  label: string;
  scope: string;
  unit: string;
  category: string;
  factor: number;
  aliases: string[]; // Kamus kata alternatif / sinonim untuk deteksi otomatis
}

export const ACTIVITY_OPTIONS: ActivityOption[] = [
  // ======================================================
  // SCOPE 1 (Direct Emissions)
  // ======================================================
  {
    value: "premium",
    label: "Premium",
    scope: "Scope 1 (Direct)",
    unit: "Liter",
    category: "Fuel",
    factor: 2.31,
    aliases: ["premium", "bensin premium", "bbm premium"],
  },
  {
    value: "pertalite",
    label: "Pertalite",
    scope: "Scope 1 (Direct)",
    unit: "Liter",
    category: "Fuel",
    factor: 2.31,
    aliases: ["pertalite", "bensin", "bensin kendaraan", "bbm", "bahan bakar"],
  },
  {
    value: "pertamax",
    label: "Pertamax",
    scope: "Scope 1 (Direct)",
    unit: "Liter",
    category: "Fuel",
    factor: 2.31,
    aliases: ["pertamax", "bensin pertamax", "pertamax 92", "pertamax plus"],
  },
  {
    value: "solar",
    label: "Solar",
    scope: "Scope 1 (Direct)",
    unit: "Liter",
    category: "Fuel",
    factor: 2.68,
    aliases: ["solar", "bahan bakar solar", "hsd", "diesel fuel"],
  },
  {
    value: "bio_solar",
    label: "Bio Solar",
    scope: "Scope 1 (Direct)",
    unit: "Liter",
    category: "Fuel",
    factor: 2.54,
    aliases: ["bio solar", "biosolar", "b30", "b35"],
  },
  {
    value: "dexlite",
    label: "Dexlite",
    scope: "Scope 1 (Direct)",
    unit: "Liter",
    category: "Fuel",
    factor: 2.68,
    aliases: ["dexlite", "bbm dexlite"],
  },
  {
    value: "pertamina_dex",
    label: "Pertamina Dex",
    scope: "Scope 1 (Direct)",
    unit: "Liter",
    category: "Fuel",
    factor: 2.68,
    aliases: ["pertamina dex", "pertaminadex", "dex"],
  },
  {
    value: "lpg",
    label: "LPG",
    scope: "Scope 1 (Direct)",
    unit: "Kg",
    category: "Gas",
    factor: 2.98,
    aliases: ["lpg", "elpiji", "gas lpg", "tabung lpg"],
  },
  {
    value: "lng",
    label: "LNG",
    scope: "Scope 1 (Direct)",
    unit: "m3",
    category: "Gas",
    factor: 2.75,
    aliases: ["lng", "liquified natural gas", "gas alam cair"],
  },
  {
    value: "cng",
    label: "CNG",
    scope: "Scope 1 (Direct)",
    unit: "m3",
    category: "Gas",
    factor: 2.75,
    aliases: ["cng", "compressed natural gas", "bbt", "bahan bakar gas"],
  },
  {
    value: "gas_alam",
    label: "Gas Alam",
    scope: "Scope 1 (Direct)",
    unit: "m3",
    category: "Gas",
    factor: 2.75,
    aliases: ["gas alam", "gas bumi", "natural gas", "gas pipa"],
  },
  {
    value: "genset_diesel",
    label: "Genset Diesel",
    scope: "Scope 1 (Direct)",
    unit: "Liter",
    category: "Generator",
    factor: 2.68,
    aliases: ["genset diesel", "solar genset", "genset solar", "generator diesel"],
  },
  {
    value: "genset_bensin",
    label: "Genset Bensin",
    scope: "Scope 1 (Direct)",
    unit: "Liter",
    category: "Generator",
    factor: 2.31,
    aliases: ["genset bensin", "generator bensin", "bensin genset"],
  },
  {
    value: "batubara",
    label: "Batubara",
    scope: "Scope 1 (Direct)",
    unit: "Kg",
    category: "Industrial Fuel",
    factor: 2.42,
    aliases: ["batubara", "batu bara", "coal", "pembakaran batubara"],
  },
  {
    value: "pelumas",
    label: "Pelumas",
    scope: "Scope 1 (Direct)",
    unit: "Liter",
    category: "Industrial",
    factor: 2.90,
    aliases: ["pelumas", "oli", "oil", "oli mesin", "pelumas mesin"],
  },

  // ======================================================
  // SCOPE 2 (Indirect - Energy)
  // ======================================================
  {
    value: "listrik_pln",
    label: "Listrik PLN",
    scope: "Scope 2 (Indirect - Energy)",
    unit: "kWh",
    category: "Electricity",
    factor: 0.85,
    aliases: ["listrik pln", "listrik", "pln", "tagihan listrik", "konsumsi listrik", "daya listrik"],
  },
  {
    value: "listrik_solar_panel",
    label: "Listrik Solar Panel",
    scope: "Scope 2 (Indirect - Energy)",
    unit: "kWh",
    category: "Renewable Energy",
    factor: 0.05,
    aliases: ["listrik solar panel", "solar panel", "plts", "panel surya", "energi surya"],
  },
  {
    value: "listrik_hidro",
    label: "Listrik Hidro",
    scope: "Scope 2 (Indirect - Energy)",
    unit: "kWh",
    category: "Renewable Energy",
    factor: 0.02,
    aliases: ["listrik hidro", "pltah", "pltb", "energi air", "hidroelektrik"],
  },
  {
    value: "listrik_angin",
    label: "Listrik Angin",
    scope: "Scope 2 (Indirect - Energy)",
    unit: "kWh",
    category: "Renewable Energy",
    factor: 0.01,
    aliases: ["listrik angin", "pltb angin", "turbin angin", "energi angin"],
  },

  // ======================================================
  // SCOPE 3 (Indirect - Value Chain)
  // ======================================================
  {
    value: "pesawat_domestik",
    label: "Pesawat Domestik",
    scope: "Scope 3 (Value Chain)",
    unit: "Km",
    category: "Transportation",
    factor: 0.12,
    aliases: ["pesawat domestik", "perjalanan pesawat", "penerbangan domestik", "pesawat", "flight domestik", "perjalanan dinas pesawat"],
  },
  {
    value: "pesawat_internasional",
    label: "Pesawat Internasional",
    scope: "Scope 3 (Value Chain)",
    unit: "Km",
    category: "Transportation",
    factor: 0.15,
    aliases: ["pesawat internasional", "penerbangan internasional", "flight internasional", "pesawat luar negeri"],
  },
  {
    value: "kereta",
    label: "Kereta",
    scope: "Scope 3 (Value Chain)",
    unit: "Km",
    category: "Transportation",
    factor: 0.04,
    aliases: ["kereta", "kereta api", "kai", "krl", "mrt", "lrt", "perjalanan kereta"],
  },
  {
    value: "bus",
    label: "Bus",
    scope: "Scope 3 (Value Chain)",
    unit: "Km",
    category: "Transportation",
    factor: 0.10,
    aliases: ["bus", "bis", "bus antar kota", "perjalanan bus", "angkutan bus"],
  },
  {
    value: "mobil_logistik",
    label: "Mobil Logistik",
    scope: "Scope 3 (Value Chain)",
    unit: "Km",
    category: "Logistics",
    factor: 0.21,
    aliases: ["mobil logistik", "van logistik", "pickup", "pick up", "mobil box", "armada logistik"],
  },
  {
    value: "truk_logistik",
    label: "Truk Logistik",
    scope: "Scope 3 (Value Chain)",
    unit: "Km",
    category: "Logistics",
    factor: 0.27,
    aliases: ["truk logistik", "truk", "truck", "truk kontainer", "fuso", "wingbox"],
  },
  {
    value: "kapal_logistik",
    label: "Kapal Logistik",
    scope: "Scope 3 (Value Chain)",
    unit: "Km",
    category: "Logistics",
    factor: 0.015,
    aliases: ["kapal logistik", "kapal kargo", "cargo ship", "pengiriman laut", "kapal laut"],
  },
  {
    value: "sampah_organik",
    label: "Sampah Organik",
    scope: "Scope 3 (Value Chain)",
    unit: "Kg",
    category: "Waste",
    factor: 0.50,
    aliases: ["sampah organik", "limbah organik", "sampah sisa makanan", "sampah dapur"],
  },
  {
    value: "sampah_anorganik",
    label: "Sampah Anorganik",
    scope: "Scope 3 (Value Chain)",
    unit: "Kg",
    category: "Waste",
    factor: 0.20,
    aliases: ["sampah anorganik", "limbah anorganik", "sampah non organik", "sampah kering"],
  },
  {
    value: "limbah_b3",
    label: "Limbah B3",
    scope: "Scope 3 (Value Chain)",
    unit: "Kg",
    category: "Hazardous Waste",
    factor: 1.80,
    aliases: ["limbah b3", "sampah b3", "limbah berbahaya", "hazardous waste", "limbah kimia"],
  },
  {
    value: "kertas",
    label: "Kertas",
    scope: "Scope 3 (Value Chain)",
    unit: "Kg",
    category: "Office Material",
    factor: 1.30,
    aliases: ["kertas", "kertas a4", "penggunaan kertas", "pembelian kertas", "rim kertas", "paper"],
  },
  {
    value: "plastik",
    label: "Plastik",
    scope: "Scope 3 (Value Chain)",
    unit: "Kg",
    category: "Material",
    factor: 2.50,
    aliases: ["plastik", "kemasan plastik", "botol plastik", "plastic"],
  },
  {
    value: "karton",
    label: "Karton",
    scope: "Scope 3 (Value Chain)",
    unit: "Kg",
    category: "Packaging",
    factor: 0.94,
    aliases: ["karton", "kardus", "box karton", "packaging karton"],
  },
  {
    value: "air_bersih",
    label: "Air Bersih",
    scope: "Scope 3 (Value Chain)",
    unit: "m3",
    category: "Water",
    factor: 0.344,
    aliases: ["air bersih", "air pdam", "pdam", "konsumsi air", "penggunaan air"],
  },
  {
    value: "air_limbah",
    label: "Air Limbah",
    scope: "Scope 3 (Value Chain)",
    unit: "m3",
    category: "Wastewater",
    factor: 0.708,
    aliases: ["air limbah", "limbah cair", "wastewater", "pengolahan air limbah"],
  },
];

// Men-generate ACTIVITY_LABELS secara dinamis menggunakan JavaScript Record reducer
export const ACTIVITY_LABELS: Record<string, string> = ACTIVITY_OPTIONS.reduce(
  (acc, cur) => {
    acc[cur.value] = cur.label;
    return acc;
  },
  {} as Record<string, string>
);